/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'askuck' at '10/27/15 12:07 PM' with Gradle 2.7
 *
 * @author askuck, @date 10/27/15 12:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
