// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systems/soapbox/wirerecord/types.proto

package systems.soapbox.wirerecord;

public final class OmbudsWireProtos {
  private OmbudsWireProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WireBulletinOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string message = 1;
    /**
     * <code>required string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    // required uint64 timestamp = 2;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    long getTimestamp();

    // optional .wirerecord.Location location = 3;
    /**
     * <code>optional .wirerecord.Location location = 3;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .wirerecord.Location location = 3;</code>
     */
    systems.soapbox.wirerecord.OmbudsWireProtos.Location getLocation();
    /**
     * <code>optional .wirerecord.Location location = 3;</code>
     */
    systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code wirerecord.WireBulletin}
   */
  public static final class WireBulletin extends
      com.google.protobuf.GeneratedMessage
      implements WireBulletinOrBuilder {
    // Use WireBulletin.newBuilder() to construct.
    private WireBulletin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WireBulletin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WireBulletin defaultInstance;
    public static WireBulletin getDefaultInstance() {
      return defaultInstance;
    }

    public WireBulletin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WireBulletin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(systems.soapbox.wirerecord.OmbudsWireProtos.Location.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireBulletin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireBulletin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.class, systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.Builder.class);
    }

    public static com.google.protobuf.Parser<WireBulletin> PARSER =
        new com.google.protobuf.AbstractParser<WireBulletin>() {
      public WireBulletin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WireBulletin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WireBulletin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>required string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional .wirerecord.Location location = 3;
    public static final int LOCATION_FIELD_NUMBER = 3;
    private systems.soapbox.wirerecord.OmbudsWireProtos.Location location_;
    /**
     * <code>optional .wirerecord.Location location = 3;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .wirerecord.Location location = 3;</code>
     */
    public systems.soapbox.wirerecord.OmbudsWireProtos.Location getLocation() {
      return location_;
    }
    /**
     * <code>optional .wirerecord.Location location = 3;</code>
     */
    public systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder getLocationOrBuilder() {
      return location_;
    }

    private void initFields() {
      message_ = "";
      timestamp_ = 0L;
      location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLocation()) {
        if (!getLocation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, location_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, location_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wirerecord.WireBulletin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireBulletin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireBulletin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.class, systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.Builder.class);
      }

      // Construct using systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (locationBuilder_ == null) {
          location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireBulletin_descriptor;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin getDefaultInstanceForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.getDefaultInstance();
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin build() {
        systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin buildPartial() {
        systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin result = new systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin) {
          return mergeFrom((systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin other) {
        if (other == systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (hasLocation()) {
          if (!getLocation().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (systems.soapbox.wirerecord.OmbudsWireProtos.WireBulletin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string message = 1;
      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      // required uint64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .wirerecord.Location location = 3;
      private systems.soapbox.wirerecord.OmbudsWireProtos.Location location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          systems.soapbox.wirerecord.OmbudsWireProtos.Location, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder, systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder> locationBuilder_;
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public systems.soapbox.wirerecord.OmbudsWireProtos.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public Builder setLocation(systems.soapbox.wirerecord.OmbudsWireProtos.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public Builder setLocation(
          systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public Builder mergeLocation(systems.soapbox.wirerecord.OmbudsWireProtos.Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              location_ != systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance()) {
            location_ =
              systems.soapbox.wirerecord.OmbudsWireProtos.Location.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      public systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_;
        }
      }
      /**
       * <code>optional .wirerecord.Location location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          systems.soapbox.wirerecord.OmbudsWireProtos.Location, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder, systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              systems.soapbox.wirerecord.OmbudsWireProtos.Location, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder, systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder>(
                  location_,
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:wirerecord.WireBulletin)
    }

    static {
      defaultInstance = new WireBulletin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:wirerecord.WireBulletin)
  }

  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double lat = 1;
    /**
     * <code>required double lat = 1;</code>
     */
    boolean hasLat();
    /**
     * <code>required double lat = 1;</code>
     */
    double getLat();

    // required double lon = 2;
    /**
     * <code>required double lon = 2;</code>
     */
    boolean hasLon();
    /**
     * <code>required double lon = 2;</code>
     */
    double getLon();

    // required double h = 3;
    /**
     * <code>required double h = 3;</code>
     */
    boolean hasH();
    /**
     * <code>required double h = 3;</code>
     */
    double getH();
  }
  /**
   * Protobuf type {@code wirerecord.Location}
   *
   * <pre>
   * A single WGS84 Datum
   * </pre>
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              lat_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lon_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              h_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              systems.soapbox.wirerecord.OmbudsWireProtos.Location.class, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double lat = 1;
    public static final int LAT_FIELD_NUMBER = 1;
    private double lat_;
    /**
     * <code>required double lat = 1;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double lat = 1;</code>
     */
    public double getLat() {
      return lat_;
    }

    // required double lon = 2;
    public static final int LON_FIELD_NUMBER = 2;
    private double lon_;
    /**
     * <code>required double lon = 2;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double lon = 2;</code>
     */
    public double getLon() {
      return lon_;
    }

    // required double h = 3;
    public static final int H_FIELD_NUMBER = 3;
    private double h_;
    /**
     * <code>required double h = 3;</code>
     */
    public boolean hasH() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double h = 3;</code>
     */
    public double getH() {
      return h_;
    }

    private void initFields() {
      lat_ = 0D;
      lon_ = 0D;
      h_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasH()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, h_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, h_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(systems.soapbox.wirerecord.OmbudsWireProtos.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wirerecord.Location}
     *
     * <pre>
     * A single WGS84 Datum
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements systems.soapbox.wirerecord.OmbudsWireProtos.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                systems.soapbox.wirerecord.OmbudsWireProtos.Location.class, systems.soapbox.wirerecord.OmbudsWireProtos.Location.Builder.class);
      }

      // Construct using systems.soapbox.wirerecord.OmbudsWireProtos.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        h_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_Location_descriptor;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Location getDefaultInstanceForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance();
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Location build() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.Location buildPartial() {
        systems.soapbox.wirerecord.OmbudsWireProtos.Location result = new systems.soapbox.wirerecord.OmbudsWireProtos.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lon_ = lon_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.h_ = h_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof systems.soapbox.wirerecord.OmbudsWireProtos.Location) {
          return mergeFrom((systems.soapbox.wirerecord.OmbudsWireProtos.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(systems.soapbox.wirerecord.OmbudsWireProtos.Location other) {
        if (other == systems.soapbox.wirerecord.OmbudsWireProtos.Location.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasH()) {
          setH(other.getH());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLon()) {
          
          return false;
        }
        if (!hasH()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        systems.soapbox.wirerecord.OmbudsWireProtos.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (systems.soapbox.wirerecord.OmbudsWireProtos.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double lat = 1;
      private double lat_ ;
      /**
       * <code>required double lat = 1;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        onChanged();
        return this;
      }

      // required double lon = 2;
      private double lon_ ;
      /**
       * <code>required double lon = 2;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double lon = 2;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>required double lon = 2;</code>
       */
      public Builder setLon(double value) {
        bitField0_ |= 0x00000002;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lon = 2;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon_ = 0D;
        onChanged();
        return this;
      }

      // required double h = 3;
      private double h_ ;
      /**
       * <code>required double h = 3;</code>
       */
      public boolean hasH() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double h = 3;</code>
       */
      public double getH() {
        return h_;
      }
      /**
       * <code>required double h = 3;</code>
       */
      public Builder setH(double value) {
        bitField0_ |= 0x00000004;
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double h = 3;</code>
       */
      public Builder clearH() {
        bitField0_ = (bitField0_ & ~0x00000004);
        h_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wirerecord.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:wirerecord.Location)
  }

  public interface WireEndorsmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes bltnid = 1;
    /**
     * <code>required bytes bltnid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    boolean hasBltnid();
    /**
     * <code>required bytes bltnid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    com.google.protobuf.ByteString getBltnid();

    // required uint64 timestamp = 2;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code wirerecord.WireEndorsment}
   */
  public static final class WireEndorsment extends
      com.google.protobuf.GeneratedMessage
      implements WireEndorsmentOrBuilder {
    // Use WireEndorsment.newBuilder() to construct.
    private WireEndorsment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WireEndorsment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WireEndorsment defaultInstance;
    public static WireEndorsment getDefaultInstance() {
      return defaultInstance;
    }

    public WireEndorsment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WireEndorsment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              bltnid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireEndorsment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireEndorsment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.class, systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.Builder.class);
    }

    public static com.google.protobuf.Parser<WireEndorsment> PARSER =
        new com.google.protobuf.AbstractParser<WireEndorsment>() {
      public WireEndorsment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WireEndorsment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WireEndorsment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes bltnid = 1;
    public static final int BLTNID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bltnid_;
    /**
     * <code>required bytes bltnid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    public boolean hasBltnid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes bltnid = 1;</code>
     *
     * <pre>
     * A 32 byte SHA hash of the referenced bulletin's txid
     * </pre>
     */
    public com.google.protobuf.ByteString getBltnid() {
      return bltnid_;
    }

    // required uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     *
     * <pre>
     * Seconds since 00:00:00 Jan 1, 1970
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      bltnid_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBltnid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, bltnid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, bltnid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wirerecord.WireEndorsment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireEndorsment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireEndorsment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.class, systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.Builder.class);
      }

      // Construct using systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bltnid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.internal_static_wirerecord_WireEndorsment_descriptor;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment getDefaultInstanceForType() {
        return systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.getDefaultInstance();
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment build() {
        systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment buildPartial() {
        systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment result = new systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bltnid_ = bltnid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment) {
          return mergeFrom((systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment other) {
        if (other == systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment.getDefaultInstance()) return this;
        if (other.hasBltnid()) {
          setBltnid(other.getBltnid());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBltnid()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (systems.soapbox.wirerecord.OmbudsWireProtos.WireEndorsment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes bltnid = 1;
      private com.google.protobuf.ByteString bltnid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bltnid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public boolean hasBltnid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes bltnid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public com.google.protobuf.ByteString getBltnid() {
        return bltnid_;
      }
      /**
       * <code>required bytes bltnid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public Builder setBltnid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bltnid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bltnid = 1;</code>
       *
       * <pre>
       * A 32 byte SHA hash of the referenced bulletin's txid
       * </pre>
       */
      public Builder clearBltnid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bltnid_ = getDefaultInstance().getBltnid();
        onChanged();
        return this;
      }

      // required uint64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       *
       * <pre>
       * Seconds since 00:00:00 Jan 1, 1970
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wirerecord.WireEndorsment)
    }

    static {
      defaultInstance = new WireEndorsment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:wirerecord.WireEndorsment)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wirerecord_WireBulletin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wirerecord_WireBulletin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wirerecord_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wirerecord_Location_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wirerecord_WireEndorsment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wirerecord_WireEndorsment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&systems/soapbox/wirerecord/types.proto" +
      "\022\nwirerecord\"Z\n\014WireBulletin\022\017\n\007message\030" +
      "\001 \002(\t\022\021\n\ttimestamp\030\002 \002(\004\022&\n\010location\030\003 \001" +
      "(\0132\024.wirerecord.Location\"/\n\010Location\022\013\n\003" +
      "lat\030\001 \002(\001\022\013\n\003lon\030\002 \002(\001\022\t\n\001h\030\003 \002(\001\"3\n\016Wir" +
      "eEndorsment\022\016\n\006bltnid\030\001 \002(\014\022\021\n\ttimestamp" +
      "\030\002 \002(\004B.\n\032systems.soapbox.wirerecordB\020Om" +
      "budsWireProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_wirerecord_WireBulletin_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_wirerecord_WireBulletin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wirerecord_WireBulletin_descriptor,
              new java.lang.String[] { "Message", "Timestamp", "Location", });
          internal_static_wirerecord_Location_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_wirerecord_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wirerecord_Location_descriptor,
              new java.lang.String[] { "Lat", "Lon", "H", });
          internal_static_wirerecord_WireEndorsment_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_wirerecord_WireEndorsment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wirerecord_WireEndorsment_descriptor,
              new java.lang.String[] { "Bltnid", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
